app:
  build: .
  command: python -u main.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: localhost
  environment:
    - MONGO_INITDB_DATABASE=bankAcme
  volumes:
    - mongo_data:/data/db
